User.create(name: "Rohit", email:"rohitpratti@gmail.com", age:23, gender:"male", location: "Seattle", password:"abc", fav_meal: "Breakfast",availability: ["Friday","Saturday"])
User.create(name: "Zema", email:"zemamail@zmail.com", age:300000, gender:"idc", location: "Seattle", password:"abc", fav_meal: "Dinner",availability: ["Saturday"])
User.create(name: "Aliya", email:"aliya@gmail.com", age:26, gender:"female", location: "Seattle", password:"abc", fav_meal: "Lunch",availability: ["Monday","Tuesday"])
User.create(name: "Wendy", email:"wendy@gmail.com", age:27, gender:"female", location: "Los Angeles", password:"abc", fav_meal: "Dinner",availability: ["Wednesday","Saturday", "Sunday"])
User.create(name: "Sarah", email:"soc33@msn.com", age:27, gender:"female", location: "Orlando", password:"abc", fav_meal: "Breakfast",availability: ["Thursday","Sunday"])
User.create(name: "Alex", email:"alex@gmail.com", age:35, gender:"male", location: "Seattle", password:"abc", fav_meal: "Dinner",availability: ["Monday","Friday"])

Restaurant.create(name:"Pagliacci", cuisine:"Italian", zipcode:98102)
Restaurant.create(name:"El Borracho", cuisine:"Mexican", zipcode:98101)
Restaurant.create(name:"Japonessa", cuisine:"Fusion", zipcode:98101)
Restaurant.create(name:"Yard House", cuisine:"American", zipcode:98101)
Restaurant.create(name:"Jasmine Thai", cuisine:"Thai", zipcode:98102)
